---
title: Whole brain microscopy analysis
subtitle: With BrainGlobe and napari
execute: 
  enabled: true
format:
    revealjs:
        theme: [default, bg-light.scss]
        logo: img/BG_logo.png
        slide-number: c
        menu:
            numbers: true
        chalkboard: true
        scrollable: true
        preview-links: false
        view-distance: 10
        mobile-view-distance: 10
        auto-animate: true
        auto-play-media: true
        code-overflow: wrap
        highlight-style: atom-one
        mermaid: 
          theme: neutral
          fontFamily: arial
          curve: linear
    html:
        theme: [default, bg-light.scss]
        logo: img/BG_logo.png
        toc: true
        code-overflow: scroll
        highlight-style: atom-one
        mermaid: 
          theme: neutral
          fontFamily: arial
          curve: linear
          margin-left: 0
        embed-resources: true
        page-layout: full
---
# Welcome

## Schedule{.smaller}
::: {.incremental}
- Installing BrainGlobe (30 mins)
- Introduction to Image analysis with Napari
- Introduction to BrainGlobe (30 mins)
- Registering whole brain microscopy images with brainreg (30 mins)
- Segmenting structures in whole brain microscopy images with brainglobe-segmentation (30 mins)
- Detecting cells in large 3D images with cellfinder (90 mins)
- Analysing cell positions in atlas space (30 mins)
- Visualisation of data in atlas space with brainrender and brainrender-napari (30 mins)
- Tour of other BrainGlobe tools and wrap-up (30 mins)
:::

# Installation

{{< include slides/installation.qmd >}}


# Image Analysis
Adapted from [https://github.com/HealthBioscienceIDEAS/microscopy-novice/](https://github.com/HealthBioscienceIDEAS/microscopy-novice/) (under CC BY 4.0 license)

{{< include slides/intro-napari.qmd >}}
{{< include slides/what-is-an-image.qmd >}}
{{< include slides/processing-images.qmd >}}


# BrainGlobe

{{< include slides/brainglobe-intro.qmd >}}
  
# Tutorials

## Registering whole brain microscopy images with brainreg

[Tutorial](https://brainglobe.info/tutorials/tutorial-whole-brain-registration.html)

## Segmenting structures in whole brain microscopy images with brainglobe-segmentation

[Tutorial (1D)](https://brainglobe.info/tutorials/segmenting-1d-tracks.html)

[Tutorial (2D/3D)](https://brainglobe.info/tutorials/segmenting-3d-structures.html)

## Detecting cells in large 3D images with cellfinder

[Cell detection tutorial](https://brainglobe.info/tutorials/cellfinder-detection.html)

[Retraining tutorial](https://brainglobe.info/tutorials/cellfinder-retraining.html)

## Analysing cell positions in atlas space

[Tutorial](https://brainglobe.info/tutorials/transform-cells-atlas.html)

## Visualisation of data in atlas space with brainrender and brainrender-napari

[Tutorial (brainrender-napari)](https://brainglobe.info/tutorials/visualise-atlas-napari.html)

[Example brainrender scripts](https://github.com/brainglobe/brainrender/tree/main/examples)

## Tour of other BrainGlobe tools and wrap-up {.smaller}
- [`brainglobe-atlasapi`](https://github.com/brainglobe/brainglobe-atlasapi)
- [`brainglobe-heatmap`](https://github.com/brainglobe/brainglobe-heatmap)
- [`brainglobe-registration`](https://github.com/brainglobe/brainglobe-registration)
- [`brainglobe-space`](https://github.com/brainglobe/brainglobe-space)
- [`brainglobe-stitch`](https://github.com/brainglobe/brainglobe-stitch)
- [`brainglobe-template-builder`](https://github.com/brainglobe/brainglobe-template-builder)
- [`brainglobe-utils`](https://github.com/brainglobe/brainglobe-utils)
- [`morphapi`](https://github.com/brainglobe/morphapi)


# Wrap up

## Resources
* [BrainGlobe website](https://brainglobe.info/){preview-link="true"}
* [Help forum](https://forum.image.sc/tag/brainglobe/){preview-link="true"}
* [Developer forum](https://brainglobe.zulipchat.com/){preview-link="true"}
* [GitHub](https://github.com/brainglobe/){preview-link="true"}

You are welcome to contribute to BrainGlobe - get in touch anytime and we will support you!

# Thank you!